server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: service-a
          uri: http://${SERVICE_A_HOST:localhost}:${SERVICE_A_PORT:8081}/savings/a/balance/
          predicates:
            - Path=/savings/a/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                exceptions:
                  - java.net.ConnectException
          order: 100
        - id: service-b
          uri: http://${SERVICE_B_HOST:localhost}:${SERVICE_B_PORT:8082}/savings/b/balance/
          predicates:
            - Path=/savings/b/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                exceptions:
                  - java.net.ConnectException
          order: 200
