version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=service-a
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5532:5432'
